tinyMCE.addI18n('es.easywave_dlg',{
title:"Easywave",
label:"Easywave",
desc_label:"Easy Wave",
desc:"Insertar codigo para google wave",
wave_id:"Id (o url) del Wave",
wave_id_desc:"Escriba aquí el Id (o la url y trataré de adivinar el Id)",
server:"URL del Servidor Wave",
server_desc:"Qué servidor de google wave usar. Sandbox: http://wave.google.com/a/wavesandbox.com/ o Preview: https://wave.google.com/wave/",
text_color:"Color de texto",
text_color_desc:"Color de texto para el wave",
bg_color:"Color de fondo",
bg_color_desc:"Color que se mostrara como fondo del wave",
font:"Fuente",
font_desc:"Selecciona la fuente por omisión.",
font_size:"Tamaño de Fuente",
font_size_desc:"Selecciona el tamaño de fuente para el wave, expresado en puntos",
width:"Ancho",
width_desc:"El ancho con que se mostrará el wave, incluyendo unidades (ej: 100% o 300px)",
height:"Alto",
height_desc:"El alto del wave, incluyendo unidades (ej: 500px o 30em)",
preview:"Previsualizar",
warning:"Cuidado: "

});